# Tratamento de erros e exceções
# try:
#     a = int(input('Numerador: '))
#     b = int(input('Denominador: '))
#     r = a / b
# # except Exception as erro:
# #     print(f'O seguinte erro encontrado foi: {erro.__class__}')
# except (ValueError, TypeError) as erro:
#     print(erro)
# else:
#     print(f'O resultado da divisão entre {a} e {b} é {r:.2f}.')
# finally:
#     print('Obrigado, volte sempre!')